### ISSUE TITLE
[WIKI]

### ISSUE THREAD

**Issue by ricardoprins** [Rishit-dagli/MakeCode-Android#8]
The 'Contributors' button design in the Wiki page doesn't match the design of the other buttons.

I'd also suggest dividing the paragraph in smaller paragraphs for improved readability.

Keep it up, bro!

-Ricardo

**Comment by Rishit-dagli** [comment]
@ricardoprins Thanks for pointing out this issue. I believe it has now been resolved, [Edited WIKI](https://github.com/Rishit-dagli/MakeCode-Android/wiki). I am closing this issue as of now, feel free to reopen this if I missed something
